[package]
name = "easy_fuser"
version = "0.1.0"
edition = "2021"

[features]
default = ["threadpool", "deadlock_detection"] # For developement
threadpool = ["dep:threadpool", "dep:num_cpus"]
deadlock_detection = []

[dependencies]
parking_lot = {version = "0.12.3", features = ["deadlock_detection"]}
log = "0.4"
libc = "0.2"
fuser = "0.15"
bitflags = "2.6.0"
threadpool = { version = "1.8", optional = true }
num_cpus = { version = "1.0", optional = true }

[dev-dependencies]
tempfile = "3.14"
env_logger = "0.11"