[package]
name = "easy_fuser"
version = "0.1.0"
edition = "2021"

[features]
default = ["parallel"] # TODO: remove
serial = []
parallel = ["dep:threadpool"]
async = []

[dependencies]
log = "0.4"
libc = "0.2"
fuser = "0.15"
bitflags = "2.6.0"
threadpool = { version = "1.8", optional = true }

[dev-dependencies]
tempfile = "3.14"