[package]
name = "passthrough_fs"
version = "0.1.2"
edition = "2021"

[dependencies]
easy_fuser = { path = "../..", features = ["serial"] }
clap = { version = "4.5", features = ["derive"] }
ctrlc = "3.4"