[package]
name = "passthrough_fs"
version = "0.1.2"
edition = "2021"
description = "A FUSE passthrough filesystem example using easy_fuser"

[dependencies]
easy_fuser = { path = "../..", features = ["parallel"] }
clap = { version = "4.5", features = ["derive"] }
ctrlc = "3.4"