[package]
name = "encrypt_fs"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
bincode = "1.3.3"
clap = { version = "4.5", features = ["derive"] }
ctrlc = "3.4"
easy_fuser = { path = "../..", features = ["parallel"] }
ring = "0.17.8"
