[package]
name = "easy_fuser_macro"
version = "0.1.1"
edition = "2024"
description = "Procedural macros for the easy_fuser crate"
license = "MIT"
repository = "https://github.com/Alogani/easy_fuser"

[lib]
proc-macro = true

[dependencies]
syn =  {version = "^3.0.6", features = [ "full" ] }
quote = "^1.0.47"
proc-macro2 = "^1.0.107"
either = "^1.18.0"
