name: Build and Release

on:
  release:
    types: [created]
  workflow_dispatch:
    branches:
      - '*'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install libfuse-dev
      run: |
        sudo apt-get update
        sudo apt-get install -y libfuse-dev

    - name: Set PKG_CONFIG_PATH
      run: echo "PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig" >> $GITHUB_ENV

    - name: Run tests of crates inside examples folder
      run: |
        mkdir bin
        for dir in examples/*/; do
          if [ -f "${dir}Cargo.toml" ]; then
            echo "Building in ${dir}"
            (
              cd "${dir}"
              cargo build --release
              example_name=$(basename "${dir}")
              cp "target/release/${example_name}" "../../bin/"
            )
          fi
        done

    - name: Upload release assets
      uses: softprops/action-gh-release@v1
      with:
        files: bin/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}