name: Nim CI ubuntu

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, devel ]

jobs:
  install_dependencies:
    name: "Install Dependencies"
    runs-on: ubuntu-latest
    steps:
    - name: Install libfuse-dev
      run: |
        sudo apt-get update
        sudo apt-get install -y libfuse-dev

  build_and_test:
    name: "ubuntu continuous integration"
    needs: install_dependencies
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - nightly
        feature:
          - serial
          - parallel
    
    steps:
    - uses: actions/checkout@v4
    - name: Setup Rust
      run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
    - name: Build
      run: cargo build --verbose --features ${{ matrix.feature }}
    - name: Run tests
      run: cargo test  --verbose --features ${{ matrix.feature }}

  test_examples:
    name: "Test Examples folder"
    needs: install_dependencies
    runs-on: ubuntu-latest
    - name: Run tests of crates inside examples folder
      run: |
        set -e
        exit_code=0
        for dir in examples/*/; do
          if [ -f "${dir}Cargo.toml" ]; then
            echo "Running tests in ${dir}"
            if ! (cd "${dir}" && cargo test); then
              echo "Tests failed in ${dir}"
              exit_code=1
            fi  
          fi
        done
        exit $exit_code