name: Nim CI ubuntu

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libfuse-dev
    - name: Build
      run: cargo build --verbose --features serial
    - name: Run tests
      run: ./tests/run_all_tests.sh
    - name: Run tests for examples
      run: |
        set -e
        exit_code=0
        for dir in examples/*/; do
          pwd
          echo "Checking directory: ${dir}"
          if [ -f "${dir}Cargo.toml" ]; then
            echo "Found Cargo.toml in ${dir}"
            echo "Running tests in ${dir}"
            if ! (cd "${dir}" && cargo test --verbose); then
              echo "Tests failed in ${dir}"
              exit_code=1
            else
              echo "Tests passed in ${dir}"
            fi  
          else
            echo "No Cargo.toml found in ${dir}"
          fi
        done
        exit $exit_code